version: '3.8'

services:
  sqmusic_main:
    image: registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus:v[version]-arm64
    container_name: sqmusic_main
    environment:
      - DB_IP=mysql
      - DB_PORT=3306
      - DB_NAME=sqmusicv3
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:?set DB_PASSWORD}
    volumes:
      - ./music:/music
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sq-app-network
    expose:
      - "8099"
    restart: always

  sqmusic_web:
    image: registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:v[webversion]-arm64
    container_name: sqmusic_web
    ports:
      - "8096:80"
    networks:
      - sq-app-network
    depends_on:
      - sqmusic_main
    restart: always

  mysql:
    image: pistar/mysql-arm:hf-5.7.25
    container_name: sqmusic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?set DB_PASSWORD}
      MYSQL_DATABASE: sqmusicv3
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sq-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  kugoumusicapi:
    build:
      context: https://github.com/MakcRe/KuGouMusicApi.git
    container_name: sqmusic_kugou_api
    ports:
      - "3000:3000"
    networks:
      - sq-app-network
    restart: unless-stopped
    environment:
      PLATFORM: lite

  neteasecloudmusicapi:
    image: registry.cn-hangzhou.aliyuncs.com/sqdockler/netease_cloud_music_api:v4.32.0
    container_name: sqmusic_netease_api
    ports:
      - "3001:3000"
    networks:
      - sq-app-network
    restart: unless-stopped

networks:
  sq-app-network:
    driver: bridge
