FROM maven:3.9.4-eclipse-temurin-21-alpine AS builder
MAINTAINER SQ

WORKDIR /build/

COPY pom.xml /build/
COPY src /build/src/

RUN mvn clean package

From mcr.microsoft.com/openjdk/jdk:21-ubuntu

# 设置默认的环境变量
#ENV DB_IP="localhost"
#ENV DB_PORT="3306"
#ENV DB_NAME="sqmusicv3"
#ENV DB_USERNAME="root"
#ENV DB_PASSWORD="root"

WORKDIR /app

# 使用通配符复制JAR文件，避免硬编码文件名
COPY --from=builder /build/target/*.jar /app/app.jar

EXPOSE 8099

VOLUME ["/music"]

CMD ["java", "-jar", "app.jar"]