CREATE TABLE IF NOT EXISTS download_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    download_gid VARCHAR(255),
    download_time TIMESTAMP,
    download_file VARCHAR(1000),
    download_music_id VARCHAR(255) NOT NULL,
    download_plug_name VARCHAR(255),
    download_br_type VARCHAR(255),
    download_musicname VARCHAR(255),
    download_artistname VARCHAR(255),
    download_albumname VARCHAR(255),
    download_msg VARCHAR(255),
    version VARCHAR(255),
    download_music_info CLOB,
    download_status VARCHAR(255),
    spring_name VARCHAR(255),
    audio_book INT,
    download_update_time TIMESTAMP,
    revision INT,
    rewrite_mp3tag INT,
    download_bits VARCHAR(255),
    download_br_types VARCHAR(255),
    parent_download_id INT,
    download_retry_num INT,
    download_retry_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_download_album ON download_info(download_albumname);
CREATE INDEX IF NOT EXISTS idx_download_artist ON download_info(download_artistname);
CREATE INDEX IF NOT EXISTS idx_download_music ON download_info(download_musicname);

CREATE TABLE IF NOT EXISTS sq_config (
    config_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(255),
    config_value CLOB,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_type VARCHAR(255),
    config_options CLOB,
    config_show INT,
    config_remark VARCHAR(1000),
    config_null_check INT,
    config_disabled INT
);

CREATE TABLE IF NOT EXISTS sq_sync (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plug_name VARCHAR(255),
    music_id VARCHAR(255),
    music_info CLOB,
    download_id INT,
    play_list_name VARCHAR(255),
    play_list_sha1 VARCHAR(255),
    play_list_id VARCHAR(255),
    artist_id VARCHAR(255),
    artist_name VARCHAR(255),
    album_id VARCHAR(255),
    album_name VARCHAR(255),
    music_name VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS sq_monitor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plug_name VARCHAR(255),
    type VARCHAR(255),
    enabled VARCHAR(32),
    target_id VARCHAR(255),
    target_name CLOB,
    target_desc CLOB,
    target_url CLOB,
    target_count BIGINT,
    target_cover CLOB,
    target_update_time BIGINT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sq_ali_sync (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sha1 VARCHAR(255),
    md5 VARCHAR(255),
    sharding_sha1 VARCHAR(255),
    `path` VARCHAR(2048),
    ali_id_path VARCHAR(255),
    ali_path VARCHAR(2048),
    `name` VARCHAR(1000),
    music_name VARCHAR(255),
    music_artist VARCHAR(255),
    music_album VARCHAR(255),
    suffix VARCHAR(32),
    upload_time TIMESTAMP,
    `result` CLOB,
    rapid INT,
    download_id INT
);
