#netease:
##  匿名登录 true 根据cookieUrl获取匿名的cookie自动填充
##  false 根据填写的cookie登录
##  anonymousLogin: true
##  baseUrl: http://cloud-music.pl-fe.cn
##  baseUrl: https://mu-api.yuk0.com
##  baseUrl: https://netease.happyking.top
##  baseUrl: http://plugin.changsheng.space:3000
##  baseUrl: https://zm.armoe.cn
##  baseUrl: https://zmusic.i9mr.com/
#   baseUrl: https://163api.qijieya.cn
#   baseUrl: http://dg-t.cn:3000
#   baseUrl: http://111.229.38.178:3333
#   baseUrl: https://wyy.xhily.com/
#   baseUrl: http://45.152.64.114:3005
#   baseUrl: http://42.193.244.179:3000
#   baseUrl: https://music-api.focalors.ltd
#   https://apis.netstart.cn/music/
#   https://www.musicapi.cn/
#   https://ilygfw-musicapi.voyage200.top/
#https://music-api.heheda.top/




https://www.musicapi.cn;http://45.152.64.114:3005;https://music-api.heheda.top;https://apis.netstart.cn/music;http://dg-t.cn:3000;https://ilygfw-musicapi.voyage200.top;https://163api.qijieya.cn;https://zm.armoe.cn;https://wyy.xhily.com;http://plugin.changsheng.space:3000;



##  cookieUrl: ${netease.baseUrl}/register/anonimous
##  cookie:
##  downloadUrl: https://csm.sayqz.com/api/?type=apiSongUrlV1&level=#{level}&id=#{id}
#
