name: 部署 Docsify 文档

on:
  push:
    branches: [ 3.0 ]
    paths:
      - src/main/resources/docs/**
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/main/resources/docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
